metastore = dict(
    file = 'data/meet_metadata.csv',
    header = [
        'id',
        'date',
        'processing_date'
        ]
    )

datastore = dict(
    file = 'data/usapl_data.csv',
    header = [
        'date',
        'meet_id',
        'meet_name',
        'meet_state',
        'event',
        'sex',
        'equipment',
        'division',
        'weight_class_kg', 
        'placing', 
        'name', 
        'lifter_yob', 
        'team', 
        'lifter_state', 
        'lot_number', 
        'lifter_weight', 
        'squat1',
        'squat2',
        'squat3',
        'bench1', 
        'bench2',
        'bench3',  
        'deadlift1', 
        'deadlift2',
        'deadlift3',
        'total', 
        'dots', 
        'drug_test'
        ]
    )

# Might be useful later
# divisions = set([
#     'Open',
#     'Open Pro',
#     'Junior',
#     'Teen',
#     'Teen 1',
#     'Teen 2',
#     'Teen 3',
#     'Teen and Junior',
#     'Sub Junior'
#     'Youth',
#     'Youth 1',
#     'Youth 2',
#     'Youth 3',
#     'Master',
#     'Master 1',
#     'Master 1a',
#     'Master 1b',
#     'Master 2',
#     'Master 2a',
#     'Master 2b',
#     'Master 3',
#     'Master 3a',
#     'Master 3b',
#     'Master 4',
#     'Master 4a',
#     'Master 4b',
#     'Master 5',
#     'Master 5a',
#     'Master 5b',
#     'Master 6',
#     'Master 6a',
#     'ParaBench',
#     'High School',
#     'High School JV',
#     'High School Varsity',
#     'Military Open',
#     'Collegiate',
#     'Police and Fire',
#     'Special Olympian',
#     'Guest Lifter',
#     'Raw Adaptive Athletes',
#     'Raw Open',
#     'Raw Open Pro',
#     'Raw Junior',
#     'Raw Teen',
#     'Raw Teen 1',
#     'Raw Teen 2',
#     'Raw Teen 3',
#     'Raw Teen and Junior',
#     'Raw Sub Junior'
#     'Raw Youth',
#     'Raw Youth 1',
#     'Raw Youth 2',
#     'Raw Youth 3',
#     'Raw Master',
#     'Raw Master 1',
#     'Raw Master 1a',
#     'Raw Master 1b',
#     'Raw Master 2',
#     'Raw Master 2a',
#     'Raw Master 2b',
#     'Raw Master 3',
#     'Raw Master 3a',
#     'Raw Master 3b',
#     'Raw Master 4',
#     'Raw Master 4a',
#     'Raw Master 4b',
#     'Raw Master 5',
#     'Raw Master 5a',
#     'Raw Master 5b',
#     'Raw Master 6',
#     'Raw Master 6a',
#     'Raw ParaBench',
#     'Raw High School',
#     'Raw High School JV',
#     'Raw High School Varsity',
#     'Raw Military Open',
#     'Raw Collegiate',
#     'Raw Police and Fire',
#     'Raw Special Olympian',
#     'Raw Guest Lifter',
# ])